### ISSUE TITLE
Newdle creation: display number of created time slots

### ISSUE THREAD

**Issue by meluru** [indico/newdle#85] opened 2019-10-01 13:16 UTC
Currently the user does't have a good overview of selected timeslots
The idea is to display the number of all currently created time slots on the page below.

![image](https://user-images.githubusercontent.com/26142639/65964638-ab631680-e45d-11e9-97e6-e6658d9894ba.png)

We could also consider listing chosen time slots (simple list with dates and times)

**Comment by pferreir** [comment] 2019-10-01 13:25
Duplicate of #79

**Closed by pferreir** 2019-10-01 13:25 UTC
